# Generated by Django 2.0.5 on 2018-08-03 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


