# Generated by Django 2.0.5 on 2018-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ph',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.TextField(default='U'),
        ),
    ]
