# Generated by Django 2.0.5 on 2018-08-16 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_board_user'),
    ]

    operations = [

    ]
