# Generated by Django 2.0.5 on 2018-08-16 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Board',
            },
        ),
    ]
