# Generated by Django 2.0.5 on 2018-08-16 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('ph', models.CharField(default='0', max_length=20)),
                ('user_role', models.CharField(default='U', max_length=20)),
                ('delete_yn', models.CharField(default='N', max_length=20)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
